<a href="https://colab.research.google.com/github/GlobalFishingWatch/gfw-api-python-client/blob/develop/notebooks/usage-guides/bulk-downloads-api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bulk Download API

This guide provides detailed instructions on how to use the [gfw-api-python-client](https://github.com/GlobalFishingWatch/gfw-api-python-client) to access the [Bulk Download API](https://globalfishingwatch.org/our-apis/documentation#bulk-download-api), which is designed to support workflows that require bulk access to data, including integration with platforms and tools used by data engineers and researchers.

**Note:** See the [Datasets](https://globalfishingwatch.org/our-apis/documentation#api-dataset), [Data Caveats](https://globalfishingwatch.org/our-apis/documentation#data-caveat), [SAR (Synthetic-Aperture Radar) Data Caveats](https://globalfishingwatch.org/our-apis/documentation#sar-fixed-infrastructure-data-caveats), and [Terms of Use](https://globalfishingwatch.org/our-apis/documentation#terms-of-use) pages in the [GFW API documentation](https://globalfishingwatch.org/our-apis/documentation#introduction) for details on GFW data, API licenses, and rate limits.

## Prerequisites

Before using the `gfw-api-python-client`, ensure it is installed (see the [Getting Started](https://globalfishingwatch.github.io/gfw-api-python-client/getting-started.html) guide) and that you have obtained an API access token from the [Global Fishing Watch API portal](https://globalfishingwatch.org/our-apis/tokens).

## Installation

The `gfw-api-python-client` can be easily installed using pip:

In [1]:
# %pip install gfw-api-python-client

## Usage

Import and use `gfw-api-python-client` in your Python codes

In [2]:
import os
import time

import geopandas as gpd

import gfwapiclient as gfw

In [3]:
try:
    from google.colab import userdata

    access_token = userdata.get("GFW_API_ACCESS_TOKEN")
except Exception:
    access_token = os.environ.get("GFW_API_ACCESS_TOKEN")

access_token = access_token or "<PASTE_YOUR_GFW_API_ACCESS_TOKEN_HERE>"

In [4]:
gfw_client = gfw.Client(
    access_token=access_token,
)

## Create a Bulk Report from Predefined Region (`create_bulk_report`)

The `create_bulk_report()` method allows you **create** a bulk report based on specified filters and spatial parameters. The `name` parameter is mandatory. Please [learn more about create a bulk report here](https://globalfishingwatch.org/our-apis/documentation#create-a-bulk-report) and [check its data caveats here](https://globalfishingwatch.org/our-apis/documentation#data-caveat) and [here](https://globalfishingwatch.org/our-apis/documentation#sar-fixed-infrastructure-data-caveats).

**Note:** See how to use the [Reference Data API - Usage Guides](https://globalfishingwatch.github.io/gfw-api-python-client/usage-guides/references-data-api.html) to obtain and filter predefined [**Regions of Interest (ROIs)**](https://globalfishingwatch.org/our-apis/documentation#regions), such as Exclusive Economic Zones (**EEZs**), Marine Protected Areas (**MPAs**), and Regional Fisheries Management Organizations (**RFMOs**).

In [5]:
eez_rois_result = await gfw_client.references.get_eez_regions(iso3="ARG")
arg_eez_roi = eez_rois_result.data()[0]

In [6]:
arg_eez_roi.id, arg_eez_roi.dataset, arg_eez_roi.label, arg_eez_roi.iso3

('8466', 'public-eez-areas', 'Argentinian Exclusive Economic Zone', 'ARG')

In [7]:
timestamp = int(time.time() * 1000)
dataset = "public-fixed-infrastructure-data:latest"
name = f"{dataset.split(':')[0]}-python-package-example-{timestamp}-predefined_region"

In [8]:
name

'public-fixed-infrastructure-data-python-package-example-1782384022398-predefined_region'

In [9]:
create_predefined_bulk_report_result = (
    await gfw_client.bulk_downloads.create_bulk_report(
        name=name,
        dataset=dataset,
        region=arg_eez_roi,
        filters=[
            "label = 'oil'",
            "label_confidence = 'high'",
            "structure_start_date between '2020-01-01' and '2025-01-01'",
        ],
    )
)

### Access Create a Bulk Report Result as Pydantic models

In [10]:
create_predefined_bulk_report_data = create_predefined_bulk_report_result.data()

In [11]:
(
    create_predefined_bulk_report_data.id,
    create_predefined_bulk_report_data.name,
    create_predefined_bulk_report_data.status,
    create_predefined_bulk_report_data.created_at,
)

('ea21f550-780b-4fa6-aa8e-158f85289492',
 'public-fixed-infrastructure-data-python-package-example-1782384022398-predefined_region',
 'pending',
 datetime.datetime(2026, 6, 25, 10, 40, 25, 113000, tzinfo=TzInfo(0)))

### Access Create a Bulk Report Result as a DataFrame

In [12]:
create_predefined_bulk_report_df = create_predefined_bulk_report_result.df()

In [13]:
create_predefined_bulk_report_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          1 non-null      str
 1   dataset     1 non-null      str
 2   name        1 non-null      str
 3   file_path   1 non-null      str
 4   format      1 non-null      str
 5   filters     1 non-null      object
 6   geom        1 non-null      object
 7   status      1 non-null      str
 8   owner_id    1 non-null      int64
 9   owner_type  1 non-null      str
 10  created_at  1 non-null      datetime64[us, UTC]
 11  updated_at  1 non-null      datetime64[us, UTC]
 12  file_size   0 non-null      object
dtypes: datetime64[us, UTC](2), int64(1), object(3), str(7)
memory usage: 236.0+ bytes

In [14]:
create_predefined_bulk_report_df.head()

,id,dataset,name,file_path,format,filters,geom,status,owner_id,owner_type,created_at,updated_at,file_size
0,ea21f550-780b-4fa6-aa8e-158f85289492,public-fixed-infrastructure-data:v1.1,public-fixed-infrastructure-data-python-packag...,sar_fixed_infrastructure_202409.csv,JSON,"[label = 'oil', label_confidence = 'high', str...","{'type': 'dataset', 'dataset': 'public-eez-are...",pending,39,application,2026-06-25 10:40:25.113000+00:00,2026-06-25 10:40:25.113000+00:00,None

## Create a Bulk Report from Custom Region (`create_bulk_report`)

The `create_bulk_report()` method allows you **create** a bulk report based on specified filters and spatial parameters. The `name` parameter is mandatory. Please [learn more about create a bulk report here](https://globalfishingwatch.org/our-apis/documentation#create-a-bulk-report) and [check its data caveats here](https://globalfishingwatch.org/our-apis/documentation#data-caveat) and [here](https://globalfishingwatch.org/our-apis/documentation#sar-fixed-infrastructure-data-caveats).

**Note:** Custom region can either a path to a spatial file (e.g., GeoJSON, Shapefile, etc.), GeoJSON-like object (e.g., JSON string, dictionary, `geopandas.GeoDataFrame`, `shapely`, an object implementing `__geo_interface__` etc.) or `GeoJson` model instance. Spatial files are loaded using [geopandas.read_file](https://geopandas.org/en/stable/docs/reference/api/geopandas.read_file.html) and supported formats depend on a properly configured [geopandas/GDAL installation](https://geopandas.org/en/stable/getting_started/install.html#installing-with-pip).

In [15]:
filename = "https://raw.githubusercontent.com/GlobalFishingWatch/gfw-api-python-client/refs/heads/develop/tests/fixtures/bulk_downloads/geojson/geojson.shp"

In [16]:
custom_roi_gdf = gpd.read_file(filename)

In [17]:
timestamp = int(time.time() * 1000)
dataset = "public-fixed-infrastructure-data:latest"
name = f"{dataset.split(':')[0]}-python-package-example-{timestamp}-custom_region"

In [18]:
name

'public-fixed-infrastructure-data-python-package-example-1782384029540-custom_region'

In [19]:
create_custom_bulk_report_result = await gfw_client.bulk_downloads.create_bulk_report(
    name=name,
    dataset=dataset,
    geojson=custom_roi_gdf,
    filters=[
        "label = 'oil'",
        "label_confidence = 'high'",
        "structure_start_date between '2020-01-01' and '2025-01-01'",
    ],
)

### Access Create a Bulk Report Result as Pydantic models

In [20]:
create_custom_bulk_report_data = create_custom_bulk_report_result.data()

In [21]:
(
    create_custom_bulk_report_data.id,
    create_custom_bulk_report_data.name,
    create_custom_bulk_report_data.status,
    create_custom_bulk_report_data.created_at,
)

('f0a39c14-1756-4f75-9150-0ada6b29eadf',
 'public-fixed-infrastructure-data-python-package-example-1782384029540-custom_region',
 'pending',
 datetime.datetime(2026, 6, 25, 10, 40, 30, 740000, tzinfo=TzInfo(0)))

### Access Create a Bulk Report Result as a DataFrame

In [22]:
create_custom_bulk_report_df = create_custom_bulk_report_result.df()

In [23]:
create_custom_bulk_report_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          1 non-null      str
 1   dataset     1 non-null      str
 2   name        1 non-null      str
 3   file_path   1 non-null      str
 4   format      1 non-null      str
 5   filters     1 non-null      object
 6   geom        1 non-null      object
 7   status      1 non-null      str
 8   owner_id    1 non-null      int64
 9   owner_type  1 non-null      str
 10  created_at  1 non-null      datetime64[us, UTC]
 11  updated_at  1 non-null      datetime64[us, UTC]
 12  file_size   0 non-null      object
dtypes: datetime64[us, UTC](2), int64(1), object(3), str(7)
memory usage: 236.0+ bytes

In [24]:
create_custom_bulk_report_df.head()

,id,dataset,name,file_path,format,filters,geom,status,owner_id,owner_type,created_at,updated_at,file_size
0,f0a39c14-1756-4f75-9150-0ada6b29eadf,public-fixed-infrastructure-data:v1.1,public-fixed-infrastructure-data-python-packag...,sar_fixed_infrastructure_202409.csv,JSON,"[label = 'oil', label_confidence = 'high', str...","{'type': 'custom', 'dataset': None, 'id': None}",pending,39,application,2026-06-25 10:40:30.740000+00:00,2026-06-25 10:40:30.740000+00:00,None

## Get Bulk Report by ID (`get_bulk_report_by_id`)

The `get_bulk_report_by_id()` method allows you retrieves **metadata and status** of the previously created bulk report based on the provided bulk report ID. The `id` parameter is mandatory. Please [learn more about get bulk report by id report here](https://globalfishingwatch.org/our-apis/documentation#get-bulk-report-by-id) and [check its data caveats here](https://globalfishingwatch.org/our-apis/documentation#data-caveat) and [here](https://globalfishingwatch.org/our-apis/documentation#sar-fixed-infrastructure-data-caveats).

 **Important:** We recommend to use this method to poll the status of previously created bulk report, if it takes **several minutes or hours** to generate until it status is `done` or `failed`.

In [25]:
bulk_report_result = await gfw_client.bulk_downloads.get_bulk_report_by_id(
    id=create_predefined_bulk_report_data.id
)

### Access Get Bulk Report by ID Result as Pydantic models

In [26]:
bulk_report_data = bulk_report_result.data()

In [27]:
(
    bulk_report_data.id,
    bulk_report_data.name,
    bulk_report_data.status,
    bulk_report_data.created_at,
)

('ea21f550-780b-4fa6-aa8e-158f85289492',
 'public-fixed-infrastructure-data-python-package-example-1782384022398-predefined_region',
 'done',
 datetime.datetime(2026, 6, 25, 10, 40, 25, 113000, tzinfo=TzInfo(0)))

### Access Get Bulk Report by ID Result as a DataFrame

In [28]:
bulk_report_df = bulk_report_result.df()

In [29]:
bulk_report_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          1 non-null      str
 1   dataset     1 non-null      str
 2   name        1 non-null      str
 3   file_path   1 non-null      str
 4   format      1 non-null      str
 5   filters     1 non-null      object
 6   geom        1 non-null      object
 7   status      1 non-null      str
 8   owner_id    1 non-null      int64
 9   owner_type  1 non-null      str
 10  created_at  1 non-null      datetime64[us, UTC]
 11  updated_at  1 non-null      datetime64[us, UTC]
 12  file_size   1 non-null      float64
dtypes: datetime64[us, UTC](2), float64(1), int64(1), object(2), str(7)
memory usage: 236.0+ bytes

In [30]:
bulk_report_df.head()

,id,dataset,name,file_path,format,filters,geom,status,owner_id,owner_type,created_at,updated_at,file_size
0,ea21f550-780b-4fa6-aa8e-158f85289492,public-fixed-infrastructure-data:v1.1,public-fixed-infrastructure-data-python-packag...,sar_fixed_infrastructure_202409.csv,JSON,"[label = 'oil', label_confidence = 'high', str...","{'type': 'dataset', 'dataset': 'public-eez-are...",done,39,application,2026-06-25 10:40:25.113000+00:00,2026-06-25 10:40:25.113000+00:00,907.0

## Get All Bulk Reports Created by User or Application (`get_all_bulk_reports`)

The `get_all_bulk_reports()` method allows you retrieves a list of **metadata and status** of the previously created bulk reports based on specified pagination, sorting, and filtering criteria. Please [learn more about get all bulk reports created by user or application here](https://globalfishingwatch.org/our-apis/documentation#get-all-bulk-reports-by-user) and [check its data caveats here](https://globalfishingwatch.org/our-apis/documentation#data-caveat) and [here](https://globalfishingwatch.org/our-apis/documentation#sar-fixed-infrastructure-data-caveats).

In [31]:
bulk_reports_result = await gfw_client.bulk_downloads.get_all_bulk_reports(
    status="done",
    dataset=dataset,
)

### Access All Created Bulk Reports Result as Pydantic models

In [32]:
bulk_reports_data = bulk_reports_result.data()

In [33]:
bulk_report_item = bulk_reports_data[-1]

In [34]:
(
    bulk_report_item.id,
    bulk_report_item.name,
    bulk_report_item.status,
    bulk_report_item.created_at,
)

('0c0cada1-72dd-4fb0-bdf6-7fe8c7fdb1e3',
 'sar-fixed-infrastructure-data-20241207-region-1',
 'done',
 datetime.datetime(2025, 12, 7, 10, 3, 12, 371000, tzinfo=TzInfo(0)))

### Access All Created Bulk Reports Result as a DataFrame

In [35]:
bulk_reports_df = bulk_reports_result.df()

In [36]:
bulk_reports_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          28 non-null     str
 1   dataset     28 non-null     str
 2   name        28 non-null     str
 3   file_path   28 non-null     str
 4   format      28 non-null     str
 5   filters     28 non-null     object
 6   geom        25 non-null     object
 7   status      28 non-null     str
 8   owner_id    28 non-null     int64
 9   owner_type  28 non-null     str
 10  created_at  28 non-null     datetime64[us, UTC]
 11  updated_at  28 non-null     datetime64[us, UTC]
 12  file_size   28 non-null     float64
dtypes: datetime64[us, UTC](2), float64(1), int64(1), object(2), str(7)
memory usage: 3.0+ KB

In [37]:
bulk_reports_df.head()

,id,dataset,name,file_path,format,filters,geom,status,owner_id,owner_type,created_at,updated_at,file_size
0,ea21f550-780b-4fa6-aa8e-158f85289492,public-fixed-infrastructure-data:v1.1,public-fixed-infrastructure-data-python-packag...,sar_fixed_infrastructure_202409.csv,JSON,"[label = 'oil', label_confidence = 'high', str...","{'type': 'dataset', 'dataset': 'public-eez-are...",done,39,application,2026-06-25 10:40:25.113000+00:00,2026-06-25 10:40:25.113000+00:00,907.0
1,125894a9-1052-4e4a-aeea-c78da72f3b11,public-fixed-infrastructure-data:v1.1,public-fixed-infrastructure-data-python-packag...,sar_fixed_infrastructure_202409.csv,JSON,"[label = 'oil', label_confidence = 'high', str...","{'type': 'custom', 'dataset': None, 'id': None}",done,39,application,2026-06-25 10:36:24.944000+00:00,2026-06-25 10:36:24.944000+00:00,25287.0
2,e01ebf90-b3e7-4657-8890-1f633fb84829,public-fixed-infrastructure-data:v1.1,public-fixed-infrastructure-data-python-packag...,sar_fixed_infrastructure_202409.csv,JSON,"[label = 'oil', label_confidence = 'high', str...","{'type': 'dataset', 'dataset': 'public-eez-are...",done,39,application,2026-06-25 10:35:58.345000+00:00,2026-06-25 10:35:58.345000+00:00,907.0
3,c44e3b52-9d54-4ebe-b9de-6867a9092a48,public-fixed-infrastructure-data:v1.1,public-fixed-infrastructure-data-python-packag...,sar_fixed_infrastructure_202409.csv,JSON,"[label = 'oil', label_confidence = 'high', str...","{'type': 'custom', 'dataset': None, 'id': None}",done,39,application,2026-06-25 10:26:37.104000+00:00,2026-06-25 10:26:37.104000+00:00,25.0
4,1188b98f-3b10-428f-9c2e-e9a51e66279c,public-fixed-infrastructure-data:v1.1,public-fixed-infrastructure-data-python-packag...,sar_fixed_infrastructure_202409.csv,JSON,"[label = 'oil', label_confidence = 'high', str...","{'type': 'dataset', 'dataset': 'public-eez-are...",done,39,application,2026-06-25 10:25:30.863000+00:00,2026-06-25 10:25:30.863000+00:00,298.0

## Get Bulk Report File Download URL (`get_bulk_report_file_download_url`)

The `get_bulk_report_file_download_url()` method allows you retrieves **signed URL** that points to a **downloadable file** hosted on Global Fishing Watch's cloud infrastructure to **download file(s)** (i.e., `"DATA"`, `"README"`, or `"GEOM"`) of the previously created bulk report. The `id` parameter is mandatory. Please [learn more about get bulk report file download url here](https://globalfishingwatch.org/our-apis/documentation#download-bulk-report-url-file) and [check its data caveats here](https://globalfishingwatch.org/our-apis/documentation#data-caveat) and [here](https://globalfishingwatch.org/our-apis/documentation#sar-fixed-infrastructure-data-caveats).

In [38]:
bulk_report_file_download_url_result = (
    await gfw_client.bulk_downloads.get_bulk_report_file_download_url(
        id=bulk_reports_data[0].id, file="DATA"
    )
)

### Access Get Bulk Report File Download URL Result as Pydantic models

In [39]:
bulk_report_file_download_url_data = bulk_report_file_download_url_result.data()

In [40]:
bulk_report_file_download_url_data.url

'https://storage.googleapis.com/gfw-api-bulk-pro-us-central1/ea21f550-780b-4fa6-aa8e-158f85289492/data.json.gz?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=api-bulk-pro%40gfw-production.iam.gserviceaccount.com%2F20260625%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260625T104032Z&X-Goog-Expires=60&X-Goog-SignedHeaders=host&X-Goog-Signature=6b9b7940e26598c8dab6cf969889d4235ceea4e59ea5412f18d40165d81891b667f9bf339ba41486d856820b0173ce430a4cd64a26b4977cb2e5856c975228e3927710078bc1b374896fc02061ab4d5ab44760299164ca4558c632200706518498507dfd6cc54bbae34bb707f3b6f91ffa1eb0d74d0fc8c0f6e34ea0a13669bb368a3c77550d143569f0722e91dd818a6d9be7fcec57036eaed7aa04cec7b1bc354308fecc623369e644839577aefae587347c395891679a1bdd3f3392de2b4edfa6e1cc6b0894da7b3f2a2ba7df5271e92801eb2479493299b0e9cba5b9b9ac604b8f18a4fb3d6f62cd6bfe56450e83fd23e8221c1afbf516abfe63081e76d9'

### Access Get Bulk Report File Download URL Result as a DataFrame

In [41]:
bulk_report_file_download_url_df = bulk_report_file_download_url_result.df()

In [42]:
bulk_report_file_download_url_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   url     1 non-null      str
dtypes: str(1)
memory usage: 140.0 bytes

In [43]:
bulk_report_file_download_url_df.iloc[0]["url"]

'https://storage.googleapis.com/gfw-api-bulk-pro-us-central1/ea21f550-780b-4fa6-aa8e-158f85289492/data.json.gz?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=api-bulk-pro%40gfw-production.iam.gserviceaccount.com%2F20260625%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260625T104032Z&X-Goog-Expires=60&X-Goog-SignedHeaders=host&X-Goog-Signature=6b9b7940e26598c8dab6cf969889d4235ceea4e59ea5412f18d40165d81891b667f9bf339ba41486d856820b0173ce430a4cd64a26b4977cb2e5856c975228e3927710078bc1b374896fc02061ab4d5ab44760299164ca4558c632200706518498507dfd6cc54bbae34bb707f3b6f91ffa1eb0d74d0fc8c0f6e34ea0a13669bb368a3c77550d143569f0722e91dd818a6d9be7fcec57036eaed7aa04cec7b1bc354308fecc623369e644839577aefae587347c395891679a1bdd3f3392de2b4edfa6e1cc6b0894da7b3f2a2ba7df5271e92801eb2479493299b0e9cba5b9b9ac604b8f18a4fb3d6f62cd6bfe56450e83fd23e8221c1afbf516abfe63081e76d9'

## Query Bulk Fixed Infrastructure Data Report (`query_bulk_fixed_infrastructure_data_report`)

The `query_bulk_fixed_infrastructure_data_report()` method allows you retrieves **data records** of a previously created **fixed infrastructure data** (i.e., `public-fixed-infrastructure-data:latest` dataset) bulk report data in JSON format based on specified pagination, sorting, and including criteria. The `id` parameter is mandatory. Please [learn more about query bulk fixed infrastructure data report in JSON format here](https://globalfishingwatch.org/our-apis/documentation#get-data-in-json-format) and [check its data caveats here](https://globalfishingwatch.org/our-apis/documentation#data-caveat) and [here](https://globalfishingwatch.org/our-apis/documentation#sar-fixed-infrastructure-data-caveats).

In [44]:
bulk_fixed_infrastructure_data_report_result = (
    await gfw_client.bulk_downloads.query_bulk_fixed_infrastructure_data_report(
        id=bulk_reports_data[0].id,
        sort="-structure_start_date",
    )
)

### Access Query Bulk Fixed Infrastructure Data Report Result as Pydantic models

In [45]:
bulk_fixed_infrastructure_data_report_data = (
    bulk_fixed_infrastructure_data_report_result.data()
)

In [46]:
bulk_fixed_infrastructure_data_report_item = bulk_fixed_infrastructure_data_report_data[
    -1
]

In [47]:
(
    bulk_fixed_infrastructure_data_report_item.structure_id,
    bulk_fixed_infrastructure_data_report_item.lat,
    bulk_fixed_infrastructure_data_report_item.lon,
    bulk_fixed_infrastructure_data_report_item.label,
    bulk_fixed_infrastructure_data_report_item.label_confidence,
)

('960880', -50.9024067539338, -69.09472856180871, 'oil', 'high')

### Access Query Bulk Fixed Infrastructure Data Report Result as a DataFrame

In [48]:
bulk_fixed_infrastructure_data_report_result_df = (
    bulk_fixed_infrastructure_data_report_result.df()
)

In [49]:
bulk_fixed_infrastructure_data_report_result_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   detection_id          30 non-null     str
 1   detection_date        31 non-null     datetime64[us]
 2   structure_id          31 non-null     str
 3   lat                   31 non-null     float64
 4   lon                   31 non-null     float64
 5   structure_start_date  31 non-null     datetime64[us]
 6   structure_end_date    7 non-null      datetime64[us]
 7   label                 31 non-null     str
 8   label_confidence      31 non-null     str
dtypes: datetime64[us](3), float64(2), str(4)
memory usage: 2.3 KB

In [50]:
bulk_fixed_infrastructure_data_report_result_df.head()

,detection_id,detection_date,structure_id,lat,lon,structure_start_date,structure_end_date,label,label_confidence
0,S1AB_AD_MEDIAN_COMP_20240601T000000_20241201T0...,2024-09-01,1051638,-53.089557,-67.322891,2024-02-01,NaT,oil,high
1,S1AB_AD_MEDIAN_COMP_20240401T000000_20241001T0...,2024-07-01,1051638,-53.089557,-67.322891,2024-02-01,NaT,oil,high
2,S1AB_AD_MEDIAN_COMP_20240301T000000_20240901T0...,2024-06-01,1051638,-53.089557,-67.322891,2024-02-01,NaT,oil,high
3,S1AB_AD_MEDIAN_COMP_20240101T000000_20240701T0...,2024-04-01,1051638,-53.089557,-67.322891,2024-02-01,NaT,oil,high
4,S1AB_AD_MEDIAN_COMP_20231101T000000_20240501T0...,2024-02-01,1051638,-53.089557,-67.322891,2024-02-01,NaT,oil,high