<a href="https://colab.research.google.com/github/GlobalFishingWatch/gfw-api-python-client/blob/develop/notebooks/usage-guides/insights-api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Insights API

This guide provides detailed instructions on how to use the [gfw-api-python-client](https://github.com/GlobalFishingWatch/gfw-api-python-client) to access aggregated insights about vessel activities through the Global Fishing Watch [Insights API](https://globalfishingwatch.org/our-apis/documentation#insights-api).

**Note:** See the [Apparent fishing detected in no-take MPAs](https://globalfishingwatch.org/our-apis/documentation#insights-api-fishing-detected-in-no-take-mpas), [Apparent fishing event detected outside known authorized areas](https://globalfishingwatch.org/our-apis/documentation#insights-api-fishing-event-detected-outside-known-authorized-areas), [Coverage](https://globalfishingwatch.org/our-apis/documentation#insights-api-coverage), [AIS off event (aka GAP)](https://globalfishingwatch.org/our-apis/documentation#insights-api-ais-off-event-aka-gap), and [RFMO IUU vessel list](https://globalfishingwatch.org/our-apis/documentation#insights-api-rfmo-iuu-vessel-list) Data Caveats — it is critical to avoid misinterpreting the insights. You can find the [Datasets](https://globalfishingwatch.org/our-apis/documentation#api-dataset), and [Terms of Use](https://globalfishingwatch.org/our-apis/documentation#terms-of-use) pages in the [GFW API documentation](https://globalfishingwatch.org/our-apis/documentation#introduction) for details on GFW data, API licenses, and rate limits.

## Prerequisites

Before using the `gfw-api-python-client`, ensure it is installed (see the [Getting Started](https://globalfishingwatch.github.io/gfw-api-python-client/getting-started.html) guide) and that you have obtained an API access token from the [Global Fishing Watch API portal](https://globalfishingwatch.org/our-apis/tokens).

## Installation

The `gfw-api-python-client` can be installed easily from either the [Python Package Index (PyPI)](https://pypi.org/project/gfw-api-python-client/) or [Conda](https://anaconda.org/conda-forge/gfw-api-python-client)

In [1]:
# %pip install gfw-api-python-client

In [1]:
# %conda install -c conda-forge gfw-api-python-client

## Usage

Import and use `gfw-api-python-client` in your Python codes

In [2]:
import os

import gfwapiclient as gfw

In [3]:
try:
    from google.colab import userdata

    access_token = userdata.get("GFW_API_ACCESS_TOKEN")
except Exception:
    access_token = os.environ.get("GFW_API_ACCESS_TOKEN")

access_token = access_token or "<PASTE_YOUR_GFW_API_ACCESS_TOKEN_HERE>"

In [4]:
gfw_client = gfw.Client(
    access_token=access_token,
)

## Getting Insights by Vessel (`get_vessel_insights`)

**Important:** `start_date` must be on or after `January 1, 2020`. [Insights](https://globalfishingwatch.org/our-apis/documentation#insights-api) are available from `January 1, 2020` onwards.

In [5]:
insights_result = await gfw_client.insights.get_vessel_insights(
    includes=["FISHING"],
    start_date="2020-01-01",
    end_date="2025-03-03",
    vessels=[
        "785101812-2127-e5d2-e8bf-7152c5259f5f",
    ],
)

### Access the insights data as Pydantic model

In [6]:
insights = insights_result.data()

In [7]:
(
    insights.period.start_date,
    insights.period.end_date,
    insights.apparent_fishing.period_selected_counters.events,
)

(datetime.date(2020, 1, 1), datetime.date(2025, 3, 3), 2829)

### Access the insights data as a DataFrame

In [8]:
insights_df = insights_result.df()

In [9]:
insights_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   period                       1 non-null      object
 1   vessel_ids_without_identity  0 non-null      object
 2   gap                          0 non-null      object
 3   coverage                     0 non-null      object
 4   apparent_fishing             1 non-null      object
 5   vessel_identity              0 non-null      object
dtypes: object(6)
memory usage: 180.0+ bytes

In [10]:
insights_df.head()

,period,vessel_ids_without_identity,gap,coverage,apparent_fishing,vessel_identity
0,"{'start_date': 2020-01-01, 'end_date': 2025-03...",None,None,None,{'datasets': ['public-global-fishing-events:v4...,None

## Getting Apparent Fishing-related Insights (`FISHING`)

In [11]:
fishing_insights_result = await gfw_client.insights.get_vessel_insights(
    includes=["FISHING"],
    start_date="2020-01-01",
    end_date="2025-03-03",
    vessels=[
        "785101812-2127-e5d2-e8bf-7152c5259f5f",
        "2339c52c3-3a84-1603-f968-d8890f23e1ed",
        "2d26aa452-2d4f-4cae-2ec4-377f85e88dcb",
    ],
)

In [12]:
fishing_insights_df = fishing_insights_result.df()

In [13]:
fishing_insights_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   period                       1 non-null      object
 1   vessel_ids_without_identity  0 non-null      object
 2   gap                          0 non-null      object
 3   coverage                     0 non-null      object
 4   apparent_fishing             1 non-null      object
 5   vessel_identity              0 non-null      object
dtypes: object(6)
memory usage: 180.0+ bytes

In [14]:
fishing_insights_df.head()

,period,vessel_ids_without_identity,gap,coverage,apparent_fishing,vessel_identity
0,"{'start_date': 2020-01-01, 'end_date': 2025-03...",None,None,None,{'datasets': ['public-global-fishing-events:v4...,None

## Getting AIS off/disabling Insights (`GAP`)

In [15]:
gap_insights_result = await gfw_client.insights.get_vessel_insights(
    includes=["GAP"],
    start_date="2020-01-01",
    end_date="2025-03-03",
    vessels=[
        "785101812-2127-e5d2-e8bf-7152c5259f5f",
        "2339c52c3-3a84-1603-f968-d8890f23e1ed",
        "2d26aa452-2d4f-4cae-2ec4-377f85e88dcb",
    ],
)

In [16]:
gap_insights_df = gap_insights_result.df()

In [17]:
gap_insights_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   period                       1 non-null      object
 1   vessel_ids_without_identity  0 non-null      object
 2   gap                          1 non-null      object
 3   coverage                     0 non-null      object
 4   apparent_fishing             0 non-null      object
 5   vessel_identity              0 non-null      object
dtypes: object(6)
memory usage: 180.0+ bytes

In [18]:
gap_insights_df.head()

,period,vessel_ids_without_identity,gap,coverage,apparent_fishing,vessel_identity
0,"{'start_date': 2020-01-01, 'end_date': 2025-03...",None,{'datasets': ['public-global-gaps-events:v4.0'...,None,None,None

## Getting AIS Coverage Metrics Insights (`COVERAGE`)

In [19]:
coverage_insights_result = await gfw_client.insights.get_vessel_insights(
    includes=["COVERAGE"],
    start_date="2020-01-01",
    end_date="2025-03-03",
    vessels=[
        "2339c52c3-3a84-1603-f968-d8890f23e1ed",
    ],
)

In [20]:
coverage_insights_df = coverage_insights_result.df()

In [21]:
coverage_insights_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   period                       1 non-null      object
 1   vessel_ids_without_identity  0 non-null      object
 2   gap                          0 non-null      object
 3   coverage                     1 non-null      object
 4   apparent_fishing             0 non-null      object
 5   vessel_identity              0 non-null      object
dtypes: object(6)
memory usage: 180.0+ bytes

In [22]:
coverage_insights_df.head()

,period,vessel_ids_without_identity,gap,coverage,apparent_fishing,vessel_identity
0,"{'start_date': 2020-01-01, 'end_date': 2025-03...",None,None,"{'blocks': '8917', 'blocks_with_positions': '7...",None,None

## Getting Being Listed in IUU (Illegal,Unreported, and Unregulated) Insights (`VESSEL-IDENTITY-IUU-VESSEL-LIST`)

In [23]:
iuu_insights_result = await gfw_client.insights.get_vessel_insights(
    includes=["VESSEL-IDENTITY-IUU-VESSEL-LIST"],
    start_date="2020-01-01",
    end_date="2025-03-03",
    vessels=[
        "2d26aa452-2d4f-4cae-2ec4-377f85e88dcb",
    ],
)

In [24]:
iuu_insights_df = iuu_insights_result.df()

In [25]:
iuu_insights_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   period                       1 non-null      object
 1   vessel_ids_without_identity  0 non-null      object
 2   gap                          0 non-null      object
 3   coverage                     0 non-null      object
 4   apparent_fishing             0 non-null      object
 5   vessel_identity              1 non-null      object
dtypes: object(6)
memory usage: 180.0+ bytes

In [26]:
iuu_insights_df.head()

,period,vessel_ids_without_identity,gap,coverage,apparent_fishing,vessel_identity
0,"{'start_date': 2020-01-01, 'end_date': 2025-03...",None,None,None,None,{'datasets': ['public-global-vessel-identity:v...

## Getting Flag Changes Insights (`VESSEL-IDENTITY-FLAG-CHANGES`)

**Note:** In order to enable this insight for your API access token (`GFW_API_ACCESS_TOKEN`), please contact apis@globalfishingwatch.org. In your message, please specify the email address used to generate the [API tokens](https://globalfishingwatch.org/our-apis/tokens) (i.e., the email address associated with your [Global Fishing Watch account](https://globalfishingwatch.org/our-apis/tokens/signup)).

In [27]:
flag_changes_insights_result = await gfw_client.insights.get_vessel_insights(
    includes=["VESSEL-IDENTITY-FLAG-CHANGES"],
    start_date="2020-01-01",
    end_date="2025-03-03",
    vessels=[
        "2d26aa452-2d4f-4cae-2ec4-377f85e88dcb",
    ],
)

In [28]:
flag_changes_insights_df = flag_changes_insights_result.df()

In [29]:
flag_changes_insights_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   period                       1 non-null      object
 1   vessel_ids_without_identity  0 non-null      object
 2   gap                          0 non-null      object
 3   coverage                     0 non-null      object
 4   apparent_fishing             0 non-null      object
 5   vessel_identity              1 non-null      object
dtypes: object(6)
memory usage: 180.0+ bytes

In [30]:
flag_changes_insights_df.head()

,period,vessel_ids_without_identity,gap,coverage,apparent_fishing,vessel_identity
0,"{'start_date': 2020-01-01, 'end_date': 2025-03...",None,None,None,None,{'datasets': ['public-global-vessel-identity:v...

## Getting Flag State Presence under Tokyo/Paris MOU black or grey Lists Insights (`VESSEL-IDENTITY-MOU-LIST`)

**Note:** In order to enable this insight for your API access token (`GFW_API_ACCESS_TOKEN`), please contact apis@globalfishingwatch.org. In your message, please specify the email address used to generate the [API tokens](https://globalfishingwatch.org/our-apis/tokens) (i.e., the email address associated with your [Global Fishing Watch account](https://globalfishingwatch.org/our-apis/tokens/signup)).

In [31]:
mou_insights_result = await gfw_client.insights.get_vessel_insights(
    includes=["VESSEL-IDENTITY-MOU-LIST"],
    start_date="2020-01-01",
    end_date="2025-03-03",
    vessels=[
        "785101812-2127-e5d2-e8bf-7152c5259f5f",
    ],
)

In [32]:
mou_insights_df = mou_insights_result.df()

In [33]:
mou_insights_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   period                       1 non-null      object
 1   vessel_ids_without_identity  0 non-null      object
 2   gap                          0 non-null      object
 3   coverage                     0 non-null      object
 4   apparent_fishing             0 non-null      object
 5   vessel_identity              1 non-null      object
dtypes: object(6)
memory usage: 180.0+ bytes

In [34]:
mou_insights_df.head()

,period,vessel_ids_without_identity,gap,coverage,apparent_fishing,vessel_identity
0,"{'start_date': 2020-01-01, 'end_date': 2025-03...",None,None,None,None,{'datasets': ['public-global-vessel-identity:v...

## Getting Multiple Insights for Multiple Vessels

**Note:** In order to enable `VESSEL-IDENTITY-FLAG-CHANGES` and `VESSEL-IDENTITY-MOU-LIST` insights for your API access token (`GFW_API_ACCESS_TOKEN`), please contact apis@globalfishingwatch.org. In your message, please specify the email address used to generate the [API tokens](https://globalfishingwatch.org/our-apis/tokens) (i.e., the email address associated with your [Global Fishing Watch account](https://globalfishingwatch.org/our-apis/tokens/signup)).

In [35]:
all_insights_result = await gfw_client.insights.get_vessel_insights(
    includes=[
        "FISHING",
        "GAP",
        "VESSEL-IDENTITY-IUU-VESSEL-LIST",
        "COVERAGE",
        "VESSEL-IDENTITY-FLAG-CHANGES",
        "VESSEL-IDENTITY-MOU-LIST",
    ],
    start_date="2020-01-01",
    end_date="2025-03-03",
    vessels=[
        "785101812-2127-e5d2-e8bf-7152c5259f5f",
        "2339c52c3-3a84-1603-f968-d8890f23e1ed",
        "2d26aa452-2d4f-4cae-2ec4-377f85e88dcb",
    ],
)

In [36]:
all_insights_df = all_insights_result.df()

In [37]:
all_insights_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   period                       1 non-null      object
 1   vessel_ids_without_identity  0 non-null      object
 2   gap                          1 non-null      object
 3   coverage                     1 non-null      object
 4   apparent_fishing             1 non-null      object
 5   vessel_identity              1 non-null      object
dtypes: object(6)
memory usage: 180.0+ bytes

In [38]:
all_insights_df.head()

,period,vessel_ids_without_identity,gap,coverage,apparent_fishing,vessel_identity
0,"{'start_date': 2020-01-01, 'end_date': 2025-03...",None,{'datasets': ['public-global-gaps-events:v4.0'...,"{'blocks': '53447', 'blocks_with_positions': '...",{'datasets': ['public-global-fishing-events:v4...,{'datasets': ['public-global-vessel-identity:v...