<a href="https://colab.research.google.com/github/GlobalFishingWatch/gfw-api-python-client/blob/develop/notebooks/usage-guides/vessels-api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vessels API

This guide provides detailed instructions on how to use the  [gfw-api-python-client](https://github.com/GlobalFishingWatch/gfw-api-python-client) to access information about vessels through the Global Fishing Watch [Vessels API](https://globalfishingwatch.org/our-apis/documentation#vessels-api).

**Note:** See the [Datasets](https://globalfishingwatch.org/our-apis/documentation#api-dataset), [Vessel Data Caveats](https://globalfishingwatch.org/our-apis/documentation#vessel-api-vessel-identity-information), and [Terms of Use](https://globalfishingwatch.org/our-apis/documentation#terms-of-use) pages in the [GFW API documentation](https://globalfishingwatch.org/our-apis/documentation#introduction) for details on GFW data, API licenses, and rate limits.

## Prerequisites

Before using the `gfw-api-python-client`, ensure it is installed (see the [Getting Started](https://globalfishingwatch.github.io/gfw-api-python-client/getting-started.html) guide) and that you have obtained an API access token from the [Global Fishing Watch API portal](https://globalfishingwatch.org/our-apis/tokens).

## Installation

The `gfw-api-python-client` can be easily installed using pip:

In [1]:
# %pip install gfw-api-python-client

In [1]:
# %conda install -c conda-forge gfw-api-python-client

## Usage

Import and use `gfw-api-python-client` in your Python codes

In [2]:
import os

import gfwapiclient as gfw

In [3]:
try:
    from google.colab import userdata

    access_token = userdata.get("GFW_API_ACCESS_TOKEN")
except Exception:
    access_token = os.environ.get("GFW_API_ACCESS_TOKEN")

access_token = access_token or "<PASTE_YOUR_GFW_API_ACCESS_TOKEN_HERE>"

In [4]:
gfw_client = gfw.Client(
    access_token=access_token,
)

**Note:** It is recommended to prioritize vessels that include both `registry_info` and `self_reported_info` (AIS), as this indicates a successful match between registry data and AIS information. See how the [Vessels API](https://globalfishingwatch.org/our-apis/documentation#vessels-api) is used in the [Vessel Viewer](https://globalfishingwatch.org/map/) [here](https://globalfishingwatch.org/our-apis/assets/2024_Vessel_Viewer_and_APIs_behind_It.pdf). Use the `vessel_ids` property of the `result` object returned by `gfw_client.vessels` methods as a shortcut to obtain the `matched vessel IDs`, which can then be passed directly to the [Insights API](https://globalfishingwatch.org/our-apis/documentation#insights-api) and [Events API](https://globalfishingwatch.org/our-apis/documentation#events-api) methods.

## Searching for Vessels (`search_vessels`)

In [5]:
vessel_search_result = await gfw_client.vessels.search_vessels(
    where="ssvid='412331038' AND imo='8775637'",
    includes=["MATCH_CRITERIA", "OWNERSHIP"],
)

### Get List of Matched Vessel IDs

In [6]:
vessel_search_result.vessel_ids

['da2b09b31-127e-27e0-fe5f-d6d87e96de6a',
 '755a48dd4-4bee-4bcf-7b5f-9baea058fc7b',
 '3dad49b0b-b2e0-9347-0c4c-e39fea560f9f']

**Note:** Use the `vessel_search_result.vessel_ids` as a shortcut to obtain the `matched vessel IDs`, which can then be passed directly to the [Insights API](https://globalfishingwatch.org/our-apis/documentation#insights-api) and [Events API](https://globalfishingwatch.org/our-apis/documentation#events-api) methods.

### Access the list of vessel as Pydantic models

In [7]:
vessel_search_data = vessel_search_result.data()

In [8]:
vessel = vessel_search_data[-1]

In [9]:
vessel.dataset, vessel.self_reported_info[-1].id

('public-global-vessel-identity:v4.0', 'da2b09b31-127e-27e0-fe5f-d6d87e96de6a')

### Access the vessels as a DataFrame

In [10]:
vessel_search_df = vessel_search_result.df()

In [11]:
vessel_search_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   dataset                         1 non-null      str
 1   registry_info_total_records     1 non-null      int64
 2   registry_info                   1 non-null      object
 3   registry_owners                 1 non-null      object
 4   registry_public_authorizations  0 non-null      object
 5   combined_sources_info           1 non-null      object
 6   self_reported_info              1 non-null      object
 7   matchCriteria                   1 non-null      object
dtypes: int64(1), object(6), str(1)
memory usage: 196.0+ bytes

In [12]:
vessel_search_df.head()

,dataset,registry_info_total_records,registry_info,registry_owners,registry_public_authorizations,combined_sources_info,self_reported_info,matchCriteria
0,public-global-vessel-identity:v4.0,1,"[{'id': '4ef90bea19300c6a23f6ce627a80238b', 's...","[{'name': 'ZHOUSHAN SHUNHANG OCEAN FISHERIES',...",None,[{'vessel_id': 'da2b09b31-127e-27e0-fe5f-d6d87...,[{'id': '755a48dd4-4bee-4bcf-7b5f-9baea058fc7b...,[{'reference': '755a48dd4-4bee-4bcf-7b5f-9baea...

## Getting a List of Vessels by IDs (`get_vessels_by_ids`)

In [13]:
vessels_result = await gfw_client.vessels.get_vessels_by_ids(
    ids=[
        "da2b09b31-127e-27e0-fe5f-d6d87e96de6a",
        "755a48dd4-4bee-4bcf-7b5f-9baea058fc7b",
        "3dad49b0b-b2e0-9347-0c4c-e39fea560f9f",
    ]
)

### Get List of Matched Vessel IDs

In [14]:
vessels_result.vessel_ids

['da2b09b31-127e-27e0-fe5f-d6d87e96de6a',
 '755a48dd4-4bee-4bcf-7b5f-9baea058fc7b',
 '3dad49b0b-b2e0-9347-0c4c-e39fea560f9f']

**Note:** Use the `vessels_result.vessel_ids` as a shortcut to obtain the `matched vessel IDs`, which can then be passed directly to the [Insights API](https://globalfishingwatch.org/our-apis/documentation#insights-api) and [Events API](https://globalfishingwatch.org/our-apis/documentation#events-api) methods.

### Access the list of vessel as Pydantic models

In [15]:
vessels_data = vessels_result.data()

In [16]:
vessel = vessels_data[-1]

In [17]:
vessel.dataset, vessel.self_reported_info[-1].id

('public-global-vessel-identity:v4.0', 'da2b09b31-127e-27e0-fe5f-d6d87e96de6a')

### Access the vessels as a DataFrame

In [18]:
vessels_df = vessels_result.df()

In [19]:
vessels_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   dataset                         1 non-null      str
 1   registry_info_total_records     1 non-null      int64
 2   registry_info                   1 non-null      object
 3   registry_owners                 1 non-null      object
 4   registry_public_authorizations  1 non-null      object
 5   combined_sources_info           1 non-null      object
 6   self_reported_info              1 non-null      object
dtypes: int64(1), object(5), str(1)
memory usage: 188.0+ bytes

In [20]:
vessels_df.head()

,dataset,registry_info_total_records,registry_info,registry_owners,registry_public_authorizations,combined_sources_info,self_reported_info
0,public-global-vessel-identity:v4.0,3,"[{'id': '4ef90bea19300c6a23f6ce627a80238b', 's...","[{'name': 'ZHOUSHAN SHUNHANG OCEAN FISHERIES',...","[{'date_from': 2017-01-04 00:00:00+00:00, 'dat...",[{'vessel_id': 'da2b09b31-127e-27e0-fe5f-d6d87...,[{'id': '755a48dd4-4bee-4bcf-7b5f-9baea058fc7b...

## Getting a Vessel by ID (`get_vessel_by_id`)

In [21]:
vessel_result = await gfw_client.vessels.get_vessel_by_id(
    id="da2b09b31-127e-27e0-fe5f-d6d87e96de6a",
)

### Get List of Matched Vessel IDs

In [22]:
vessel_result.vessel_ids

['da2b09b31-127e-27e0-fe5f-d6d87e96de6a',
 '755a48dd4-4bee-4bcf-7b5f-9baea058fc7b',
 '3dad49b0b-b2e0-9347-0c4c-e39fea560f9f']

**Note:** Use the `vessel_result.vessel_ids` as a shortcut to obtain the `matched vessel IDs`, which can then be passed directly to the [Insights API](https://globalfishingwatch.org/our-apis/documentation#insights-api) and [Events API](https://globalfishingwatch.org/our-apis/documentation#events-api) methods.

### Access the vessel as Pydantic model

In [23]:
vessel = vessel_result.data()

In [24]:
vessel.dataset, vessel.self_reported_info[-1].id

('public-global-vessel-identity:v4.0', 'da2b09b31-127e-27e0-fe5f-d6d87e96de6a')

### Access the vessel as a DataFrame

In [25]:
vessel_df = vessel_result.df()

In [26]:
vessel_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   dataset                         1 non-null      str
 1   registry_info_total_records     1 non-null      int64
 2   registry_info                   1 non-null      object
 3   registry_owners                 1 non-null      object
 4   registry_public_authorizations  1 non-null      object
 5   combined_sources_info           1 non-null      object
 6   self_reported_info              1 non-null      object
dtypes: int64(1), object(5), str(1)
memory usage: 188.0+ bytes

In [27]:
vessel_df.head()

,dataset,registry_info_total_records,registry_info,registry_owners,registry_public_authorizations,combined_sources_info,self_reported_info
0,public-global-vessel-identity:v4.0,3,"[{'id': '4ef90bea19300c6a23f6ce627a80238b', 's...","[{'name': 'ZHOUSHAN SHUNHANG OCEAN FISHERIES',...","[{'date_from': 2017-01-04 00:00:00+00:00, 'dat...",[{'vessel_id': 'da2b09b31-127e-27e0-fe5f-d6d87...,[{'id': '755a48dd4-4bee-4bcf-7b5f-9baea058fc7b...